apiVersion: v1
kind: Service
metadata:
  name: player-service
  namespace: player
spec:
  selector:
    app: player
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000